name: mobile_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  awesome_extensions: ^2.0.10
  shimmer: ^3.0.0
  dio: ^5.3.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  expand_tap_area: ^1.1.1
  keyboard_service: ^2.0.2
  go_router: ^12.1.1
  flutter_native_splash: ^2.3.5
  intl_phone_field: ^3.2.0
  flutter_animate: ^4.2.0+1
  gif_view: ^0.4.0
  dashed_circular_progress_bar: ^0.0.6
  pinput: ^3.0.1
  percent_indicator: ^4.2.3
  country_picker: ^2.0.22

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/svgs/

  uses-material-design: true
