name: duduzili
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: 5.8.4
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  awesome_extensions: ^2.0.10
  shimmer: ^3.0.0
  dio: ^5.3.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  expand_tap_area: ^1.1.1
  keyboard_service: ^2.0.2
  go_router: ^12.1.1
  flutter_native_splash: ^2.3.5
  intl_phone_field: ^3.2.0
  flutter_animate: ^4.2.0+1
  gif_view: ^0.4.0
  dashed_circular_progress_bar: ^0.0.6
  pinput: ^3.0.1
  percent_indicator: ^4.2.3
  country_picker: ^2.0.22
  status_view: ^0.0.2
  # audioplayers: ^5.2.1
  audio_video_progress_bar: ^2.0.1
  just_audio: ^0.9.36
  flutter_media_metadata: ^1.0.0+1
  video_player: ^2.8.1
  detectable_text_field: ^2.1.0
  camerawesome: ^2.0.0
  flutter_story_view: ^0.0.3
  dropdown_button2: ^2.3.9
  get_it: ^7.6.4
  easy_localization: ^3.0.3
  web_socket_client: ^0.1.0
  web_socket_channel: ^2.4.0
  internet_connection_checker: ^1.0.0+1
  timeago: ^3.6.0
  flutter_dotenv: ^5.1.0
  encrypt: ^5.0.3
  h3m_shimmer_card: ^0.0.2
  dartz: ^0.10.1
  pretty_dio_logger: ^1.3.1
  firebase_performance_dio: ^0.6.0
  local_auth: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/svgs/
    - assets/audio/
    - assets/video/

  uses-material-design: true
